import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./provider";
import dbConnect from "./lib/mongodb";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sticker Saver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  dbConnect()
  return (
    <html lang="en">
      <body className={inter.className} >
        <AuthProvider>
          <Navbar />


          {children}
        </AuthProvider>

      </body>
    </html>
  );
}
